services:

  coreservice_db:
    hostname: coreservice_db
    image: postgres:15
    restart: unless-stopped
    command: [ "postgres", "-c", "max_prepared_transactions=1" ]
    environment:
      - POSTGRES_USER=${POSTGRES_DB_LOGIN}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      timeout: 2s
      retries: 15

  coreservice_service:
    working_dir: /code/src
    command: uvicorn --log-level debug app:app --host $APP_HOST --port $APP_PORT --reload
    build:
      context: ../
      dockerfile: Dockerfile
    depends_on:
      coreservice_db:
        condition: service_healthy
    environment:
      - POSTGRES_DB_LOGIN
      - POSTGRES_DB_PASSWORD
      - POSTGRES_DB_HOST=coreservice_db
      - POSTGRES_DB_PORT=5432
      - POSTGRES_DB_NAME
      - SQLALCHEMY_ECHO
      - SQLALCHEMY_POOL_SIZE
      - LOGGING_LEVEL
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ../src/app:/code/src/app
